@{
    RootModule                = 'sqlshell.psm1'
    ModuleVersion             = '0.1.000'
    GUID                      = 'e9fc9e6c-4f35-4a85-9372-92df6125c6f5'
    Author                    = 'Constantine Kokkinos'
    CompanyName               = 'sqlshell'
    Copyright                 = '2017 Constantine Kokkinos'
    Description               = "Lightweight SQL Server querying and automation framework"
    PowerShellVersion         = '5.1'
    FunctionsToExport         = @(
       'Backup-Database'
      ,'Connect-Instance'
      ,'ConvertTo-DataTable'
      ,'Copy-Credential'
      ,'Copy-Database'
      ,'Copy-DatabaseAssembly'
      ,'Copy-DatabaseMail'
      ,'Copy-ExtendedEvent'
      ,'Copy-LinkedServer'
      ,'Copy-Login'
      ,'Copy-SysDbUserObject'
      ,'Copy-TableData'
      ,'Expand-TLogResponsibly'
      ,'Find-Backup'
      ,'Find-Object'
      ,'Find-OrphanedFile'
      ,'Find-UserObject'
      ,'Get-BackupDevice'
      ,'Get-ClientProtocol'
      ,'Get-DefaultPath'
      ,'Get-LastBackup'
      ,'Get-LastGoodCheckDb'
      ,'Get-NetworkActivity'
      ,'Get-ServerProtocol'
      ,'Get-Spn'
      ,'Get-SqlRegistryRoot'
      ,'Get-TempdbUsage'
      ,'Invoke-SqlCmd2'
      ,'Read-BackupHeader'
      ,'Remove-DatabaseSafely'
      ,'Remove-Spn'
      ,'Repair-OrphanUser'
      ,'Reset-Admin'
      ,'Restart-SqlService'
      ,'Restore-Database'
      ,'Set-PowerPlan'
      ,'Set-StartupParameter'
      ,'Stop-Process'
      ,'Stop-SqlService'
      ,'Test-CmConnection'
      ,'Test-Connection'
      ,'Test-PowerPlan'
      ,'Test-Spn'
      ,'Write-DataTable'
      ,'Invoke-GlobalConfig'
      ,'Get-GlobalConfig'
    )
    CmdletsToExport           = '*'
    VariablesToExport         = '*'
    AliasesToExport           = @()
    ModuleList                = @()
    FileList                  = ''
    DefaultCommandPrefix      = 'Sq'
}